$axure.loadCurrentPage({
  "url":"regist.html",
  "generationDate":new Date(1398431701288.18),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"yz_msg",
"DroplistOption"],
  "page":{
    "packageId":"10a7b1cbea9143dea31546fb9b680341",
    "type":"Axure:Page",
    "name":"regist",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"fa09ba3658364854a6beee13275e67c1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Microsoft Sans Serif Normal', 'Microsoft Sans Serif'",
            "fontSize":"14px",
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":262,
              "y":52},
            "size":{
              "width":295,
              "height":380},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "linePattern":"dashed",
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6d5c5793530482899a7562d7291aa19",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Microsoft Sans Serif Normal', 'Microsoft Sans Serif'",
                "fontSize":"14px",
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":262,
                  "y":52},
                "size":{
                  "width":295,
                  "height":380},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "linePattern":"dashed",
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/timeline/u0.png"}},
{
          "id":"bd890a10dd4a401cb6a8b97c011712f9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFF00CCCC},
            "location":{
              "x":264,
              "y":52},
            "size":{
              "width":293,
              "height":41},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"42848e327c5b41c7b43344a13b8ef2b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00CCCC},
                "location":{
                  "x":264,
                  "y":52},
                "size":{
                  "width":293,
                  "height":41},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/timeline/u2.png"}},
{
          "id":"503c217854244cc8a3b571592582ccde",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Microsoft Sans Serif Normal', 'Microsoft Sans Serif'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":277,
              "y":130},
            "size":{
              "width":150,
              "height":17},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d4b9783223a74429b597cd296ea4d90e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Microsoft Sans Serif Normal', 'Microsoft Sans Serif'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "location":{
                  "x":277,
                  "y":130},
                "size":{
                  "width":150,
                  "height":17},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"14aaee38b0d642cba3b18fee3b4d975b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Microsoft Sans Serif Normal', 'Microsoft Sans Serif'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":277,
              "y":164},
            "size":{
              "width":150,
              "height":17},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"56ababf25433486fb4f55231b1f60632",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Microsoft Sans Serif Normal', 'Microsoft Sans Serif'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "location":{
                  "x":277,
                  "y":164},
                "size":{
                  "width":150,
                  "height":17},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"84d5a216adf14f84bf219663dcb3b94d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Microsoft Sans Serif Normal', 'Microsoft Sans Serif'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":277,
              "y":199},
            "size":{
              "width":150,
              "height":17},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca181eb5f8ac472d9f574b1d6d466191",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Microsoft Sans Serif Normal', 'Microsoft Sans Serif'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "location":{
                  "x":277,
                  "y":199},
                "size":{
                  "width":150,
                  "height":17},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"89222adae9ee425f8386eea55955cb4c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Microsoft Sans Serif Normal', 'Microsoft Sans Serif'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":277,
              "y":230},
            "size":{
              "width":150,
              "height":17},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e72f840ac26a4f98a76ed42fcbef0060",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Microsoft Sans Serif Normal', 'Microsoft Sans Serif'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "location":{
                  "x":277,
                  "y":230},
                "size":{
                  "width":150,
                  "height":17},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1f5ac0c8e092471f8063a8bc8c6b5181",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Droid Sans Regular', 'Droid Sans'",
            "fontSize":"21px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":70,
              "y":430},
            "size":{
              "width":150,
              "height":26},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d99489cacb2f4046bc3b969b83e4a8f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Droid Sans Regular', 'Droid Sans'",
                "fontSize":"21px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":70,
                  "y":430},
                "size":{
                  "width":150,
                  "height":26},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0e1302ddbb5446afb763219247723b9c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Microsoft Sans Serif Normal', 'Microsoft Sans Serif'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":277,
              "y":261},
            "size":{
              "width":150,
              "height":17},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7762e28a266243dc984d9b47588b37df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Microsoft Sans Serif Normal', 'Microsoft Sans Serif'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "location":{
                  "x":277,
                  "y":261},
                "size":{
                  "width":150,
                  "height":17},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9132e9d7f2f94c5c8991ad27e5a2a428",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Microsoft Sans Serif Normal', 'Microsoft Sans Serif'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":277,
              "y":293},
            "size":{
              "width":150,
              "height":17},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"709ad3837a364deca3908c8a1d4b5e53",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Microsoft Sans Serif Normal', 'Microsoft Sans Serif'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "location":{
                  "x":277,
                  "y":293},
                "size":{
                  "width":150,
                  "height":17},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"596495fa83134f4eb1d07ef1c34f70fd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":359,
              "y":386},
            "size":{
              "width":99,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0435f14a2c524902b3ba2c91a8d73e4d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":359,
                  "y":386},
                "size":{
                  "width":99,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Show regist_submit_ok fade 500 ms",
                      "objectsToFades":[{
                          "objectPath":["08d7ee0db433487cbf9f2e0c593b006e"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"fade",
                              "duration":500,
                              "showType":"none"}}}]}]},
{
                  "description":"Case 2",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open timeline in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"timeline.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/person_info/u20.png"}},
{
          "id":"540fc3942a7a4619ba10b628b664c81c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Droid Sans Regular', 'Droid Sans'",
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "location":{
              "x":365,
              "y":397},
            "size":{
              "width":82,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f26218fc1354189b82e27db4a1ce933",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Droid Sans Regular', 'Droid Sans'",
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "location":{
                  "x":365,
                  "y":397},
                "size":{
                  "width":82,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cd24a7604fd64c948de3d008a9b15a45",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Microsoft Sans Serif Normal', 'Microsoft Sans Serif'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":277,
              "y":323},
            "size":{
              "width":150,
              "height":17},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"81189ac2e2424885b904284ea98bab1a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Microsoft Sans Serif Normal', 'Microsoft Sans Serif'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "location":{
                  "x":277,
                  "y":323},
                "size":{
                  "width":150,
                  "height":17},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"74bfb10badcc4578a628e1dfb6b8c321",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Microsoft Sans Serif Normal', 'Microsoft Sans Serif'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":277,
              "y":351},
            "size":{
              "width":150,
              "height":17},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9422e4ca6dc04d678cc0ae272b9e28ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Microsoft Sans Serif Normal', 'Microsoft Sans Serif'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "location":{
                  "x":277,
                  "y":351},
                "size":{
                  "width":150,
                  "height":17},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b3fc4ade8f5f4510b76ba421ef10e0e7",
          "label":"province",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":228},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"de44a1aaf43f4e389690dd4b9e4e1bcb",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":341,
              "y":130},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"3e8a5b62e96a43a88c2466a2063c426e",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":341,
              "y":163},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"982d6c14e30d46e2b713302803551696",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":341,
              "y":196},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"f8844ee20a9140cfba65738328a4ccf5",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":341,
              "y":261},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"37921fc362b64c85a349226d090b21c2",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":341,
              "y":322},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"20ea1300618047ca8c1207ecd8736d84",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":341,
              "y":352},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"c0fd37b5682b4dbf8de255732063ef0e",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":341,
              "y":294},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"18c4b8e1f7b24c08adb698f3fcae0064",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":341,
                  "y":294},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"1e88e02b55fa46ba91fd7c4d7ac6f1af",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":394,
              "y":295},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"95f2594d59d64d29a354e1293f35a07f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":394,
                  "y":295},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"5a89cbf29d4b40d98699f45995afdaa3",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":451,
              "y":295},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9c42551d26964b0792318c2ab11c1923",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":451,
                  "y":295},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"7ea1760e21fe402ba05a2115e41130eb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":261,
              "y":59},
            "size":{
              "width":19,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bf13c3bf3df04150ab209dce17c094c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":261,
                  "y":59},
                "size":{
                  "width":19,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open timeline in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"timeline.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/msginfo/u12.png"}},
{
          "id":"08d7ee0db433487cbf9f2e0c593b006e",
          "label":"regist_submit_ok",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":620,
              "y":334.5},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b0262ce15fd8401691c44f4054160962",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":620,
                  "y":334.5},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/regist/regist_submit_ok_u41.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "fa09ba3658364854a6beee13275e67c1":{
      "scriptId":"u0"},
    "a6d5c5793530482899a7562d7291aa19":{
      "scriptId":"u1"},
    "bd890a10dd4a401cb6a8b97c011712f9":{
      "scriptId":"u2"},
    "42848e327c5b41c7b43344a13b8ef2b3":{
      "scriptId":"u3"},
    "503c217854244cc8a3b571592582ccde":{
      "scriptId":"u4"},
    "d4b9783223a74429b597cd296ea4d90e":{
      "scriptId":"u5"},
    "14aaee38b0d642cba3b18fee3b4d975b":{
      "scriptId":"u6"},
    "56ababf25433486fb4f55231b1f60632":{
      "scriptId":"u7"},
    "84d5a216adf14f84bf219663dcb3b94d":{
      "scriptId":"u8"},
    "ca181eb5f8ac472d9f574b1d6d466191":{
      "scriptId":"u9"},
    "89222adae9ee425f8386eea55955cb4c":{
      "scriptId":"u10"},
    "e72f840ac26a4f98a76ed42fcbef0060":{
      "scriptId":"u11"},
    "1f5ac0c8e092471f8063a8bc8c6b5181":{
      "scriptId":"u12"},
    "d99489cacb2f4046bc3b969b83e4a8f4":{
      "scriptId":"u13"},
    "0e1302ddbb5446afb763219247723b9c":{
      "scriptId":"u14"},
    "7762e28a266243dc984d9b47588b37df":{
      "scriptId":"u15"},
    "9132e9d7f2f94c5c8991ad27e5a2a428":{
      "scriptId":"u16"},
    "709ad3837a364deca3908c8a1d4b5e53":{
      "scriptId":"u17"},
    "596495fa83134f4eb1d07ef1c34f70fd":{
      "scriptId":"u18"},
    "0435f14a2c524902b3ba2c91a8d73e4d":{
      "scriptId":"u19"},
    "540fc3942a7a4619ba10b628b664c81c":{
      "scriptId":"u20"},
    "5f26218fc1354189b82e27db4a1ce933":{
      "scriptId":"u21"},
    "cd24a7604fd64c948de3d008a9b15a45":{
      "scriptId":"u22"},
    "81189ac2e2424885b904284ea98bab1a":{
      "scriptId":"u23"},
    "74bfb10badcc4578a628e1dfb6b8c321":{
      "scriptId":"u24"},
    "9422e4ca6dc04d678cc0ae272b9e28ec":{
      "scriptId":"u25"},
    "b3fc4ade8f5f4510b76ba421ef10e0e7":{
      "scriptId":"u26"},
    "de44a1aaf43f4e389690dd4b9e4e1bcb":{
      "scriptId":"u27"},
    "3e8a5b62e96a43a88c2466a2063c426e":{
      "scriptId":"u28"},
    "982d6c14e30d46e2b713302803551696":{
      "scriptId":"u29"},
    "f8844ee20a9140cfba65738328a4ccf5":{
      "scriptId":"u30"},
    "37921fc362b64c85a349226d090b21c2":{
      "scriptId":"u31"},
    "20ea1300618047ca8c1207ecd8736d84":{
      "scriptId":"u32"},
    "c0fd37b5682b4dbf8de255732063ef0e":{
      "scriptId":"u33"},
    "18c4b8e1f7b24c08adb698f3fcae0064":{
      "scriptId":"u34"},
    "1e88e02b55fa46ba91fd7c4d7ac6f1af":{
      "scriptId":"u35"},
    "95f2594d59d64d29a354e1293f35a07f":{
      "scriptId":"u36"},
    "5a89cbf29d4b40d98699f45995afdaa3":{
      "scriptId":"u37"},
    "9c42551d26964b0792318c2ab11c1923":{
      "scriptId":"u38"},
    "7ea1760e21fe402ba05a2115e41130eb":{
      "scriptId":"u39"},
    "bf13c3bf3df04150ab209dce17c094c5":{
      "scriptId":"u40"},
    "08d7ee0db433487cbf9f2e0c593b006e":{
      "scriptId":"u41"},
    "b0262ce15fd8401691c44f4054160962":{
      "scriptId":"u42"}}});