$axure.loadCurrentPage({
  "url":"person_info.html",
  "generationDate":new Date(1397661642956.83),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"yz_msg",
"DroplistOption"],
  "page":{
    "packageId":"70d911d80afc4db9888260a36669a15b",
    "type":"Axure:Page",
    "name":"person_info",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"fa09ba3658364854a6beee13275e67c1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Microsoft Sans Serif Normal', 'Microsoft Sans Serif'",
            "fontSize":"14px",
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":262,
              "y":52},
            "size":{
              "width":295,
              "height":380},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "linePattern":"dashed",
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6d5c5793530482899a7562d7291aa19",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Microsoft Sans Serif Normal', 'Microsoft Sans Serif'",
                "fontSize":"14px",
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":262,
                  "y":52},
                "size":{
                  "width":295,
                  "height":380},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "linePattern":"dashed",
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/timeline/u0.png"}},
{
          "id":"bd890a10dd4a401cb6a8b97c011712f9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFF00CCCC},
            "location":{
              "x":264,
              "y":52},
            "size":{
              "width":293,
              "height":41},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"42848e327c5b41c7b43344a13b8ef2b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00CCCC},
                "location":{
                  "x":264,
                  "y":52},
                "size":{
                  "width":293,
                  "height":41},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/timeline/u2.png"}},
{
          "id":"503c217854244cc8a3b571592582ccde",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Microsoft Sans Serif Normal', 'Microsoft Sans Serif'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":277,
              "y":130},
            "size":{
              "width":150,
              "height":17},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d4b9783223a74429b597cd296ea4d90e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Microsoft Sans Serif Normal', 'Microsoft Sans Serif'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "location":{
                  "x":277,
                  "y":130},
                "size":{
                  "width":150,
                  "height":17},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"14aaee38b0d642cba3b18fee3b4d975b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Microsoft Sans Serif Normal', 'Microsoft Sans Serif'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":277,
              "y":164},
            "size":{
              "width":150,
              "height":17},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"56ababf25433486fb4f55231b1f60632",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Microsoft Sans Serif Normal', 'Microsoft Sans Serif'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "location":{
                  "x":277,
                  "y":164},
                "size":{
                  "width":150,
                  "height":17},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"84d5a216adf14f84bf219663dcb3b94d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Microsoft Sans Serif Normal', 'Microsoft Sans Serif'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":277,
              "y":199},
            "size":{
              "width":150,
              "height":17},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca181eb5f8ac472d9f574b1d6d466191",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Microsoft Sans Serif Normal', 'Microsoft Sans Serif'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "location":{
                  "x":277,
                  "y":199},
                "size":{
                  "width":150,
                  "height":17},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"89222adae9ee425f8386eea55955cb4c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Microsoft Sans Serif Normal', 'Microsoft Sans Serif'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":277,
              "y":230},
            "size":{
              "width":150,
              "height":17},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e72f840ac26a4f98a76ed42fcbef0060",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Microsoft Sans Serif Normal', 'Microsoft Sans Serif'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "location":{
                  "x":277,
                  "y":230},
                "size":{
                  "width":150,
                  "height":17},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1f5ac0c8e092471f8063a8bc8c6b5181",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Droid Sans Regular', 'Droid Sans'",
            "fontSize":"21px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":70,
              "y":430},
            "size":{
              "width":150,
              "height":26},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d99489cacb2f4046bc3b969b83e4a8f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Droid Sans Regular', 'Droid Sans'",
                "fontSize":"21px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":70,
                  "y":430},
                "size":{
                  "width":150,
                  "height":26},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0e1302ddbb5446afb763219247723b9c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Microsoft Sans Serif Normal', 'Microsoft Sans Serif'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":277,
              "y":261},
            "size":{
              "width":150,
              "height":17},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7762e28a266243dc984d9b47588b37df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Microsoft Sans Serif Normal', 'Microsoft Sans Serif'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "location":{
                  "x":277,
                  "y":261},
                "size":{
                  "width":150,
                  "height":17},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e0dd5866733943d3a413d9b39f00970a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":261,
              "y":59},
            "size":{
              "width":19,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe0f5e74cda54d66b838511a83dc6ad5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":261,
                  "y":59},
                "size":{
                  "width":19,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open timeline in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"timeline.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/msginfo/u21.png"}},
{
          "id":"9132e9d7f2f94c5c8991ad27e5a2a428",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Microsoft Sans Serif Normal', 'Microsoft Sans Serif'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":277,
              "y":293},
            "size":{
              "width":150,
              "height":17},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"709ad3837a364deca3908c8a1d4b5e53",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Microsoft Sans Serif Normal', 'Microsoft Sans Serif'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "location":{
                  "x":277,
                  "y":293},
                "size":{
                  "width":150,
                  "height":17},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"596495fa83134f4eb1d07ef1c34f70fd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":360,
              "y":370},
            "size":{
              "width":99,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0435f14a2c524902b3ba2c91a8d73e4d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":360,
                  "y":370},
                "size":{
                  "width":99,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/person_info/u20.png"}},
{
          "id":"540fc3942a7a4619ba10b628b664c81c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Droid Sans Regular', 'Droid Sans'",
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "location":{
              "x":366,
              "y":382},
            "size":{
              "width":82,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f26218fc1354189b82e27db4a1ce933",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Droid Sans Regular', 'Droid Sans'",
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "location":{
                  "x":366,
                  "y":382},
                "size":{
                  "width":82,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cd24a7604fd64c948de3d008a9b15a45",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Microsoft Sans Serif Normal', 'Microsoft Sans Serif'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":277,
              "y":323},
            "size":{
              "width":53,
              "height":17},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"81189ac2e2424885b904284ea98bab1a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Microsoft Sans Serif Normal', 'Microsoft Sans Serif'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "location":{
                  "x":277,
                  "y":323},
                "size":{
                  "width":53,
                  "height":17},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c6edff8a09de4103a683ca97bdfcae3e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Microsoft Sans Serif Normal', 'Microsoft Sans Serif'",
            "fontSize":"14px",
            "underline":true,
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":321,
              "y":323},
            "size":{
              "width":53,
              "height":17},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ff195b6a1a046d5bea08e4980c6ca8b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Microsoft Sans Serif Normal', 'Microsoft Sans Serif'",
                "fontSize":"14px",
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":321,
                  "y":323},
                "size":{
                  "width":53,
                  "height":17},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "fa09ba3658364854a6beee13275e67c1":{
      "scriptId":"u0"},
    "a6d5c5793530482899a7562d7291aa19":{
      "scriptId":"u1"},
    "bd890a10dd4a401cb6a8b97c011712f9":{
      "scriptId":"u2"},
    "42848e327c5b41c7b43344a13b8ef2b3":{
      "scriptId":"u3"},
    "503c217854244cc8a3b571592582ccde":{
      "scriptId":"u4"},
    "d4b9783223a74429b597cd296ea4d90e":{
      "scriptId":"u5"},
    "14aaee38b0d642cba3b18fee3b4d975b":{
      "scriptId":"u6"},
    "56ababf25433486fb4f55231b1f60632":{
      "scriptId":"u7"},
    "84d5a216adf14f84bf219663dcb3b94d":{
      "scriptId":"u8"},
    "ca181eb5f8ac472d9f574b1d6d466191":{
      "scriptId":"u9"},
    "89222adae9ee425f8386eea55955cb4c":{
      "scriptId":"u10"},
    "e72f840ac26a4f98a76ed42fcbef0060":{
      "scriptId":"u11"},
    "1f5ac0c8e092471f8063a8bc8c6b5181":{
      "scriptId":"u12"},
    "d99489cacb2f4046bc3b969b83e4a8f4":{
      "scriptId":"u13"},
    "0e1302ddbb5446afb763219247723b9c":{
      "scriptId":"u14"},
    "7762e28a266243dc984d9b47588b37df":{
      "scriptId":"u15"},
    "e0dd5866733943d3a413d9b39f00970a":{
      "scriptId":"u16"},
    "fe0f5e74cda54d66b838511a83dc6ad5":{
      "scriptId":"u17"},
    "9132e9d7f2f94c5c8991ad27e5a2a428":{
      "scriptId":"u18"},
    "709ad3837a364deca3908c8a1d4b5e53":{
      "scriptId":"u19"},
    "596495fa83134f4eb1d07ef1c34f70fd":{
      "scriptId":"u20"},
    "0435f14a2c524902b3ba2c91a8d73e4d":{
      "scriptId":"u21"},
    "540fc3942a7a4619ba10b628b664c81c":{
      "scriptId":"u22"},
    "5f26218fc1354189b82e27db4a1ce933":{
      "scriptId":"u23"},
    "cd24a7604fd64c948de3d008a9b15a45":{
      "scriptId":"u24"},
    "81189ac2e2424885b904284ea98bab1a":{
      "scriptId":"u25"},
    "c6edff8a09de4103a683ca97bdfcae3e":{
      "scriptId":"u26"},
    "4ff195b6a1a046d5bea08e4980c6ca8b":{
      "scriptId":"u27"}}});