$axure.loadCurrentPage({
  "url":"whoami.html",
  "generationDate":new Date(1397661641009.72),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"yz_msg",
"DroplistOption"],
  "page":{
    "packageId":"5d553e18e01247319ec25030a3bb829f",
    "type":"Axure:Page",
    "name":"WhoAmI",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[]}},
  "masters":{
},
  "objectPaths":{
}});