$axure.loadCurrentPage({
  "url":"msginfo.html",
  "generationDate":new Date(1397661642913.83),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"yz_msg",
"DroplistOption"],
  "page":{
    "packageId":"61ed44ac6e0c437c8b938ad4e5f98ac3",
    "type":"Axure:Page",
    "name":"msginfo",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"fa09ba3658364854a6beee13275e67c1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":260,
              "y":69},
            "size":{
              "width":295,
              "height":380},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "linePattern":"dashed",
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6d5c5793530482899a7562d7291aa19",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":260,
                  "y":69},
                "size":{
                  "width":295,
                  "height":380},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "linePattern":"dashed",
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/timeline/u0.png"}},
{
          "id":"bd890a10dd4a401cb6a8b97c011712f9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFF00CCCC},
            "location":{
              "x":261,
              "y":70},
            "size":{
              "width":293,
              "height":41},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"42848e327c5b41c7b43344a13b8ef2b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00CCCC},
                "location":{
                  "x":261,
                  "y":70},
                "size":{
                  "width":293,
                  "height":41},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/timeline/u2.png"}},
{
          "id":"503c217854244cc8a3b571592582ccde",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Microsoft Sans Serif Normal', 'Microsoft Sans Serif'",
            "fontSize":"19px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":277,
              "y":126},
            "size":{
              "width":150,
              "height":24},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d4b9783223a74429b597cd296ea4d90e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Microsoft Sans Serif Normal', 'Microsoft Sans Serif'",
                "fontSize":"19px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "location":{
                  "x":277,
                  "y":126},
                "size":{
                  "width":150,
                  "height":24},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"14aaee38b0d642cba3b18fee3b4d975b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Microsoft Sans Serif Normal', 'Microsoft Sans Serif'",
            "fontSize":"19px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":276,
              "y":151},
            "size":{
              "width":150,
              "height":24},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"56ababf25433486fb4f55231b1f60632",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Microsoft Sans Serif Normal', 'Microsoft Sans Serif'",
                "fontSize":"19px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "location":{
                  "x":276,
                  "y":151},
                "size":{
                  "width":150,
                  "height":24},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1f5ac0c8e092471f8063a8bc8c6b5181",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Droid Sans Regular', 'Droid Sans'",
            "fontSize":"21px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":70,
              "y":430},
            "size":{
              "width":150,
              "height":26},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d99489cacb2f4046bc3b969b83e4a8f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Droid Sans Regular', 'Droid Sans'",
                "fontSize":"21px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":70,
                  "y":430},
                "size":{
                  "width":150,
                  "height":26},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0e1302ddbb5446afb763219247723b9c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Microsoft Sans Serif Normal', 'Microsoft Sans Serif'",
            "fontSize":"19px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":277,
              "y":176},
            "size":{
              "width":150,
              "height":24},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7762e28a266243dc984d9b47588b37df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Microsoft Sans Serif Normal', 'Microsoft Sans Serif'",
                "fontSize":"19px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "location":{
                  "x":277,
                  "y":176},
                "size":{
                  "width":150,
                  "height":24},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"172523e657d942d4b4a3e1a58427c4fb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":512,
              "y":66},
            "size":{
              "width":42,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e29a9faf6f7e4aa7a63c71655b9f049a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":512,
                  "y":66},
                "size":{
                  "width":42,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Show msg_info_del_popup",
                      "objectsToFades":[{
                          "objectPath":["31838459019f4380a8e2d8eabc81f061"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/msginfo/u12.png"}},
{
          "id":"31838459019f4380a8e2d8eabc81f061",
          "label":"msg_info_del_popup",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":573,
              "y":92},
            "size":{
              "width":320,
              "height":145},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"579e153f8b1c442f9e8e467764fdea90",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":573,
                  "y":92},
                "size":{
                  "width":320,
                  "height":145},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/msginfo/msg_info_del_popup_u14.png"}},
{
          "id":"ce953e906af041b9b1f2d195128cfb92",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":583,
              "y":187},
            "size":{
              "width":150,
              "height":40}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open timeline in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"timeline.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"d1303bf1c53044a48f6c7e1cd2665b5f",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":743,
              "y":187},
            "size":{
              "width":140,
              "height":40}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open msginfo in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"msginfo.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"6b60ad44e8434dd9b793ff471b71a1c9",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":573,
              "y":172},
            "size":{
              "width":320,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/msginfo/u18_line.png"}},
{
          "id":"631f26a556234a5bbf12d50021270c4f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":593,
              "y":117},
            "size":{
              "width":280,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f5243e32f6f488884603de7a985839c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":593,
                  "y":117},
                "size":{
                  "width":280,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"45c73b271d0d45e28d89776f4205e7ef",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":261,
              "y":76},
            "size":{
              "width":19,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"83a07109452f4b24a016b85c595a713b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":261,
                  "y":76},
                "size":{
                  "width":19,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open timeline in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"timeline.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/msginfo/u21.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "fa09ba3658364854a6beee13275e67c1":{
      "scriptId":"u0"},
    "a6d5c5793530482899a7562d7291aa19":{
      "scriptId":"u1"},
    "bd890a10dd4a401cb6a8b97c011712f9":{
      "scriptId":"u2"},
    "42848e327c5b41c7b43344a13b8ef2b3":{
      "scriptId":"u3"},
    "503c217854244cc8a3b571592582ccde":{
      "scriptId":"u4"},
    "d4b9783223a74429b597cd296ea4d90e":{
      "scriptId":"u5"},
    "14aaee38b0d642cba3b18fee3b4d975b":{
      "scriptId":"u6"},
    "56ababf25433486fb4f55231b1f60632":{
      "scriptId":"u7"},
    "1f5ac0c8e092471f8063a8bc8c6b5181":{
      "scriptId":"u8"},
    "d99489cacb2f4046bc3b969b83e4a8f4":{
      "scriptId":"u9"},
    "0e1302ddbb5446afb763219247723b9c":{
      "scriptId":"u10"},
    "7762e28a266243dc984d9b47588b37df":{
      "scriptId":"u11"},
    "172523e657d942d4b4a3e1a58427c4fb":{
      "scriptId":"u12"},
    "e29a9faf6f7e4aa7a63c71655b9f049a":{
      "scriptId":"u13"},
    "31838459019f4380a8e2d8eabc81f061":{
      "scriptId":"u14"},
    "579e153f8b1c442f9e8e467764fdea90":{
      "scriptId":"u15"},
    "ce953e906af041b9b1f2d195128cfb92":{
      "scriptId":"u16"},
    "d1303bf1c53044a48f6c7e1cd2665b5f":{
      "scriptId":"u17"},
    "6b60ad44e8434dd9b793ff471b71a1c9":{
      "scriptId":"u18"},
    "631f26a556234a5bbf12d50021270c4f":{
      "scriptId":"u19"},
    "7f5243e32f6f488884603de7a985839c":{
      "scriptId":"u20"},
    "45c73b271d0d45e28d89776f4205e7ef":{
      "scriptId":"u21"},
    "83a07109452f4b24a016b85c595a713b":{
      "scriptId":"u22"}}});