$axure.loadCurrentPage({
  "url":"msginfo.html",
  "generationDate":new Date(1398431701192.17),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"yz_msg",
"DroplistOption"],
  "page":{
    "packageId":"61ed44ac6e0c437c8b938ad4e5f98ac3",
    "type":"Axure:Page",
    "name":"msginfo",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"fa09ba3658364854a6beee13275e67c1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":259,
              "y":66},
            "size":{
              "width":295,
              "height":380},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "linePattern":"dashed",
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6d5c5793530482899a7562d7291aa19",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":259,
                  "y":66},
                "size":{
                  "width":295,
                  "height":380},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "linePattern":"dashed",
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/timeline/u0.png"}},
{
          "id":"bd890a10dd4a401cb6a8b97c011712f9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFF00CCCC},
            "location":{
              "x":260,
              "y":67},
            "size":{
              "width":293,
              "height":41},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"42848e327c5b41c7b43344a13b8ef2b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00CCCC},
                "location":{
                  "x":260,
                  "y":67},
                "size":{
                  "width":293,
                  "height":41},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/timeline/u2.png"}},
{
          "id":"503c217854244cc8a3b571592582ccde",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Microsoft Sans Serif Normal', 'Microsoft Sans Serif'",
            "fontSize":"19px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":277,
              "y":126},
            "size":{
              "width":150,
              "height":24},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d4b9783223a74429b597cd296ea4d90e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Microsoft Sans Serif Normal', 'Microsoft Sans Serif'",
                "fontSize":"19px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "location":{
                  "x":277,
                  "y":126},
                "size":{
                  "width":150,
                  "height":24},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"14aaee38b0d642cba3b18fee3b4d975b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Microsoft Sans Serif Normal', 'Microsoft Sans Serif'",
            "fontSize":"19px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":276,
              "y":151},
            "size":{
              "width":150,
              "height":24},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"56ababf25433486fb4f55231b1f60632",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Microsoft Sans Serif Normal', 'Microsoft Sans Serif'",
                "fontSize":"19px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "location":{
                  "x":276,
                  "y":151},
                "size":{
                  "width":150,
                  "height":24},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0e1302ddbb5446afb763219247723b9c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Rage Italic', 'Rage'",
            "fontSize":"19px",
            "fontStyle":"italic",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "location":{
              "x":277,
              "y":190},
            "size":{
              "width":150,
              "height":24},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7762e28a266243dc984d9b47588b37df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Rage Italic', 'Rage'",
                "fontSize":"19px",
                "fontStyle":"italic",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "location":{
                  "x":277,
                  "y":190},
                "size":{
                  "width":150,
                  "height":24},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"631f26a556234a5bbf12d50021270c4f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":593,
              "y":117},
            "size":{
              "width":280,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f5243e32f6f488884603de7a985839c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":593,
                  "y":117},
                "size":{
                  "width":280,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"45c73b271d0d45e28d89776f4205e7ef",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":261,
              "y":76},
            "size":{
              "width":19,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"83a07109452f4b24a016b85c595a713b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":261,
                  "y":76},
                "size":{
                  "width":19,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open timeline in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"timeline.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/msginfo/u12.png"}},
{
          "id":"ad6baeff422c4790afde7122027af8d9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":277,
              "y":175},
            "size":{
              "width":130,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b2ef82ae638c4af39fe1097e61adffa5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":277,
                  "y":175},
                "size":{
                  "width":130,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"48b8799e14fa4a1abd12cfdca6013faf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Microsoft Sans Serif Normal', 'Microsoft Sans Serif'",
            "fontSize":"19px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":273,
              "y":312},
            "size":{
              "width":150,
              "height":24},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7418b7c5fc7747e18c39b63c26ac19ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Microsoft Sans Serif Normal', 'Microsoft Sans Serif'",
                "fontSize":"19px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "location":{
                  "x":273,
                  "y":312},
                "size":{
                  "width":150,
                  "height":24},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f27d03fb749649a8b5a92cd66fc28e82",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Microsoft Sans Serif Normal', 'Microsoft Sans Serif'",
            "fontSize":"19px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":272,
              "y":337},
            "size":{
              "width":150,
              "height":24},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ca4f08d2f444602b3bead1692d634ba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Microsoft Sans Serif Normal', 'Microsoft Sans Serif'",
                "fontSize":"19px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "location":{
                  "x":272,
                  "y":337},
                "size":{
                  "width":150,
                  "height":24},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"99a8e889acaf4bd4b3252be26ebb602c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Rage Italic', 'Rage'",
            "fontSize":"19px",
            "fontStyle":"italic",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":273,
              "y":377},
            "size":{
              "width":150,
              "height":24},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b79bef6153c645deaf412522b3496554",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Rage Italic', 'Rage'",
                "fontSize":"19px",
                "fontStyle":"italic",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "location":{
                  "x":273,
                  "y":377},
                "size":{
                  "width":150,
                  "height":24},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e13632113b174f35916bcef8bdfaa747",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":273,
              "y":363},
            "size":{
              "width":130,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e34c3bd7a12d4118949d34311ca14ef6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":273,
                  "y":363},
                "size":{
                  "width":130,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f20283180618485bbe676f77b7923c2d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":511,
              "y":62.5},
            "size":{
              "width":42,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9cdd7c5817df4ef6ac4a5023088edc2b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":511,
                  "y":62.5},
                "size":{
                  "width":42,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Show delmsg_popup",
                      "objectsToFades":[{
                          "objectPath":["e708d350956240c1a797c1e631948619"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/msginfo/u24.png"}},
{
          "id":"e708d350956240c1a797c1e631948619",
          "label":"delmsg_popup",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":582,
              "y":110},
            "size":{
              "width":320,
              "height":145},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"21c581cca9674932a657e03e302e739a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":582,
                  "y":110},
                "size":{
                  "width":320,
                  "height":145},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/msginfo/delmsg_popup_u26.png"}},
{
          "id":"e31df1287bca4fa0a744c7e78cde6be8",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":592,
              "y":204},
            "size":{
              "width":150,
              "height":40}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open timeline in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"timeline.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"b64b55c349c340d2af5cfd649ff44d7f",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":752,
              "y":204},
            "size":{
              "width":140,
              "height":40}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open msginfo in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"msginfo.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"3c1f6d146d1c4867b596e19b2bca3bb3",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":582,
              "y":190},
            "size":{
              "width":320,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/msginfo/u30_line.png"}},
{
          "id":"75315de8c5cf4cc9b235f7ef41fa1b28",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":602,
              "y":134},
            "size":{
              "width":280,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bf0c027b61204fa0a9581c07845461e2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":602,
                  "y":134},
                "size":{
                  "width":280,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8cf62cf66c024e3282b7d9b1f25de0c8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":261,
              "y":411},
            "size":{
              "width":229,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"36cdf872fc624992ad0721ed11e166df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":261,
                  "y":411},
                "size":{
                  "width":229,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u2.png"}},
{
          "id":"b43b9e4602c1426da7a343e716b5ef9d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Droid Sans Regular', 'Droid Sans'",
            "fontSize":"16px",
            "location":{
              "x":268,
              "y":421},
            "size":{
              "width":176,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a736b9bdb01f440faa7f1ac75b26d44e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Droid Sans Regular', 'Droid Sans'",
                "fontSize":"16px",
                "location":{
                  "x":268,
                  "y":421},
                "size":{
                  "width":176,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b6591e6145fb462c84d8c51bed553026",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'宋体 Bold', '宋体'",
            "fontSize":"16px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFFECA2C},
{
                      "color":0xFFFECA2C},
{
                      "color":0xFFE89C00},
{
                      "color":0xFFEBA203},
{
                      "color":0xFFF6BE15},
{
                      "color":0xFFF6BE15}]}},
              "mouseDown":{
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFFDA343},
{
                      "color":0xFFFDA343},
{
                      "color":0xFFF06600},
{
                      "color":0xFFF06600},
{
                      "color":0xFFF2A14A},
{
                      "color":0xFFF2A14A}]}}},
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFF3F3F3},
{
                  "color":0xFFF3F3F3},
{
                  "color":0xFFCACACA},
{
                  "color":0xFFCDCDCD},
{
                  "color":0xFFCDCDCD}]},
            "location":{
              "x":495,
              "y":414},
            "size":{
              "width":53,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"adf8335d530f444b8f9fd860cdb3d4ab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Bold', '宋体'",
                "fontSize":"16px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"linearGradient",
                      "colors":[{
                          "color":0xFFFECA2C},
{
                          "color":0xFFFECA2C},
{
                          "color":0xFFE89C00},
{
                          "color":0xFFEBA203},
{
                          "color":0xFFF6BE15},
{
                          "color":0xFFF6BE15}]}},
                  "mouseDown":{
                    "fill":{
                      "fillType":"linearGradient",
                      "colors":[{
                          "color":0xFFFDA343},
{
                          "color":0xFFFDA343},
{
                          "color":0xFFF06600},
{
                          "color":0xFFF06600},
{
                          "color":0xFFF2A14A},
{
                          "color":0xFFF2A14A}]}}},
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFF3F3F3},
{
                      "color":0xFFF3F3F3},
{
                      "color":0xFFCACACA},
{
                      "color":0xFFCDCDCD},
{
                      "color":0xFFCDCDCD}]},
                "location":{
                  "x":495,
                  "y":414},
                "size":{
                  "width":53,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/msginfo/u37.png",
            "mouseOver~":"images/msginfo/u37_mouseOver.png",
            "mouseDown~":"images/msginfo/u37_mouseDown.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "fa09ba3658364854a6beee13275e67c1":{
      "scriptId":"u0"},
    "a6d5c5793530482899a7562d7291aa19":{
      "scriptId":"u1"},
    "bd890a10dd4a401cb6a8b97c011712f9":{
      "scriptId":"u2"},
    "42848e327c5b41c7b43344a13b8ef2b3":{
      "scriptId":"u3"},
    "503c217854244cc8a3b571592582ccde":{
      "scriptId":"u4"},
    "d4b9783223a74429b597cd296ea4d90e":{
      "scriptId":"u5"},
    "14aaee38b0d642cba3b18fee3b4d975b":{
      "scriptId":"u6"},
    "56ababf25433486fb4f55231b1f60632":{
      "scriptId":"u7"},
    "0e1302ddbb5446afb763219247723b9c":{
      "scriptId":"u8"},
    "7762e28a266243dc984d9b47588b37df":{
      "scriptId":"u9"},
    "631f26a556234a5bbf12d50021270c4f":{
      "scriptId":"u10"},
    "7f5243e32f6f488884603de7a985839c":{
      "scriptId":"u11"},
    "45c73b271d0d45e28d89776f4205e7ef":{
      "scriptId":"u12"},
    "83a07109452f4b24a016b85c595a713b":{
      "scriptId":"u13"},
    "ad6baeff422c4790afde7122027af8d9":{
      "scriptId":"u14"},
    "b2ef82ae638c4af39fe1097e61adffa5":{
      "scriptId":"u15"},
    "48b8799e14fa4a1abd12cfdca6013faf":{
      "scriptId":"u16"},
    "7418b7c5fc7747e18c39b63c26ac19ac":{
      "scriptId":"u17"},
    "f27d03fb749649a8b5a92cd66fc28e82":{
      "scriptId":"u18"},
    "6ca4f08d2f444602b3bead1692d634ba":{
      "scriptId":"u19"},
    "99a8e889acaf4bd4b3252be26ebb602c":{
      "scriptId":"u20"},
    "b79bef6153c645deaf412522b3496554":{
      "scriptId":"u21"},
    "e13632113b174f35916bcef8bdfaa747":{
      "scriptId":"u22"},
    "e34c3bd7a12d4118949d34311ca14ef6":{
      "scriptId":"u23"},
    "f20283180618485bbe676f77b7923c2d":{
      "scriptId":"u24"},
    "9cdd7c5817df4ef6ac4a5023088edc2b":{
      "scriptId":"u25"},
    "e708d350956240c1a797c1e631948619":{
      "scriptId":"u26"},
    "21c581cca9674932a657e03e302e739a":{
      "scriptId":"u27"},
    "e31df1287bca4fa0a744c7e78cde6be8":{
      "scriptId":"u28"},
    "b64b55c349c340d2af5cfd649ff44d7f":{
      "scriptId":"u29"},
    "3c1f6d146d1c4867b596e19b2bca3bb3":{
      "scriptId":"u30"},
    "75315de8c5cf4cc9b235f7ef41fa1b28":{
      "scriptId":"u31"},
    "bf0c027b61204fa0a9581c07845461e2":{
      "scriptId":"u32"},
    "8cf62cf66c024e3282b7d9b1f25de0c8":{
      "scriptId":"u33"},
    "36cdf872fc624992ad0721ed11e166df":{
      "scriptId":"u34"},
    "b43b9e4602c1426da7a343e716b5ef9d":{
      "scriptId":"u35"},
    "a736b9bdb01f440faa7f1ac75b26d44e":{
      "scriptId":"u36"},
    "b6591e6145fb462c84d8c51bed553026":{
      "scriptId":"u37"},
    "adf8335d530f444b8f9fd860cdb3d4ab":{
      "scriptId":"u38"}}});